# Generated by Django 3.1 on 2020-08-12 22:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('company_location', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
